[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn portify.wsgi:application --bind 0.0.0.0:$PORT --workers 3"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
